FROM node:24-alpine AS builder
ARG NODE_ENV=development
WORKDIR /builder
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN corepack enable
RUN pnpm ci
COPY . .
RUN pnpm build --configuration="$NODE_ENV"

FROM nginxinc/nginx-unprivileged:alpine AS frontend
COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY --chown=nginx:nginx --from=builder /builder/dist/angular-transaction-tracker/browser /usr/share/nginx/html
USER nginx
EXPOSE 8080
ENTRYPOINT ["nginx", "-c", "/etc/nginx/nginx.conf"]
CMD ["-g", "daemon off;"]